"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { initialOnboarding, OnboardingData, steps, ChannelState } from "../lib-onboarding";

const sources=["Google", "AI assistant", "LinkedIn", "Partner", "Friend", "Other"];
const goals=[["Customer support","Answer questions and route conversations."],["Appointment booking","Help customers find and confirm the next slot."],["Sales and follow-up","Keep every lead moving with useful context."],["Operations automation","Take repeatable work off your team’s plate."],["Governance and review","Move faster while keeping people in charge."]];
const assistants=[["Inbound support","Answer questions, greet customers, and take messages.","☎"],["Outbound follow-up","Sales calls, reminders, and proactive updates.","↗"],["Internal team assistant","Help your team find sources and complete repeat work.","✦"],["Custom workflow","Describe what you want to build and start from there.","{}"]];
const channels=["Website","WhatsApp","Voice","SMS","API / SDK","Knowledge connectors"];

export function OnboardingFlow(){
  const [data,setData]=useState<OnboardingData>(initialOnboarding);const [step,setStep]=useState(0);const [error,setError]=useState("");const [loaded,setLoaded]=useState(false);
  useEffect(()=>{try{const saved=localStorage.getItem("aegis-onboarding");if(saved)setData({...initialOnboarding,...JSON.parse(saved)});}catch{}setLoaded(true)},[]);
  useEffect(()=>{if(loaded)localStorage.setItem("aegis-onboarding",JSON.stringify(data))},[data,loaded]);
  const update=(patch:Partial<OnboardingData>)=>setData(current=>({...current,...patch}));
  const required=useMemo(()=>step===0&&(!data.name.trim()||!data.email.trim()),[step,data]);
  function next(){if(required){setError("Add your name and email to continue.");return}setError("");setStep(Math.min(step+1,steps.length-1))}function back(){setError("");setStep(Math.max(step-1,0))}
  return <div className="onboarding-page"><aside className="onboarding-rail"><span className="eyebrow">Aegis / first run</span><h1>Build a useful workspace.</h1><p>Start with a few details. Change the boundaries as your team learns what to trust.</p><div className="stepper" aria-label="Onboarding progress">{steps.map((item,index)=><div className={`step ${index===step?"active":""} ${index<step?"done":""}`} key={item}><span className="step-dot">{index<step?"✓":index+1}</span><div><b>{item}</b><small>{stepDescription(index)}</small></div></div>)}</div></aside><section className="onboarding-panel" aria-live="polite"><header><span className="eyebrow">Step {step+1} of {steps.length}</span><h2>{stepTitle(step)}</h2><p>{stepSubtitle(step)}</p></header>{stepContent(step,data,update)}{error&&<p className="error" role="alert">{error}</p>}<div className="onboarding-actions">{step>0?<button className="button ghost" onClick={back} type="button">← Back</button>:<Link className="button ghost" href="/">Exit setup</Link>}{step<steps.length-1?<><button className="button" onClick={next} type="button">Continue ↗</button></>:<Link className="button" href="/product">Continue to workspace ↗</Link>}</div></section></div>
}
function stepDescription(i:number){return ["A little about you","Shape your workspace","Choose the outcome","Set a useful starting point","What Aegis prepares","Connect when ready","Review and begin"][i]}
function stepTitle(i:number){return ["Welcome to Aegis","Tell us about your work","What should Aegis help with first?","Choose a starting point","We’ve prepared a few things","Connect your channels","Your workspace is ready to shape"][i]}
function stepSubtitle(i:number){return ["This gives us enough context to make your first workspace useful.","These details help us recommend the right workflows and defaults.","You can change this later. Start with the outcome that matters now.","Choose a type to get started, or describe what you need.","Aegis creates a governed starting point so your team can review before anything moves.","Connect what you use today. Everything else can be set up later inside your workspace.","Here’s the shape of your first run. Nothing has been provisioned yet."][i]}
function stepContent(step:number,data:OnboardingData,update:(patch:Partial<OnboardingData>)=>void){
 if(step===0)return <div className="form-stack"><div className="field"><label htmlFor="name">What’s your full name? <span>REQUIRED</span></label><input id="name" value={data.name} onChange={e=>update({name:e.target.value})} autoComplete="name" /></div><div className="field"><label htmlFor="email">Work email <span>REQUIRED</span></label><input id="email" type="email" value={data.email} onChange={e=>update({email:e.target.value})} autoComplete="email" /></div><div className="field"><label htmlFor="role">What’s your role?</label><input id="role" placeholder="e.g. Operations lead" value={data.role} onChange={e=>update({role:e.target.value})} /></div><div className="field"><label>How did you find Aegis? <span>OPTIONAL</span></label><div className="choice-grid three">{sources.map(source=><button type="button" className={`choice ${data.source===source?"selected":""}`} onClick={()=>update({source})} key={source}><strong>{source}</strong></button>)}</div></div></div>;
 if(step===1)return <div className="form-stack"><div className="field-grid"><div className="field"><label htmlFor="company">Company name</label><input id="company" value={data.company} onChange={e=>update({company:e.target.value})}/></div><div className="field"><label htmlFor="website">Website</label><input id="website" placeholder="https://" value={data.website} onChange={e=>update({website:e.target.value})}/></div></div><div className="field-grid"><div className="field"><label htmlFor="language">Language</label><select id="language" value={data.language} onChange={e=>update({language:e.target.value})}><option>English</option><option>French</option><option>Spanish</option></select></div><div className="field"><label htmlFor="timezone">Timezone</label><select id="timezone" value={data.timezone} onChange={e=>update({timezone:e.target.value})}><option>Africa/Accra</option><option>Europe/London</option><option>America/New_York</option></select></div></div><div className="field"><label>Industry</label><div className="choice-grid">{["Banking & Fintech","Healthcare","Insurance","Telecom","Retail","Professional Services"].map(item=><button type="button" className={`choice ${data.industry===item?"selected":""}`} onClick={()=>update({industry:item})} key={item}><strong>{item}</strong></button>)}</div></div><div className="field"><label>Company size</label><div className="choice-grid three">{["1–20","21–100","101–500","501–2,000","2,000+"] .map(item=><button type="button" className={`choice ${data.size===item?"selected":""}`} onClick={()=>update({size:item})} key={item}><strong>{item}</strong><small>people</small></button>)}</div></div></div>;
 if(step===2)return <div className="choice-grid">{goals.map(([title,copy])=><button type="button" className={`choice ${data.goal===title?"selected":""}`} onClick={()=>update({goal:title})} key={title}><span className="choice-icon">✦</span><strong>{title}</strong><small>{copy}</small></button>)}</div>;
 if(step===3)return <div className="form-stack"><div className="choice-grid">{assistants.map(([title,copy,icon])=><button type="button" className={`choice ${data.assistant===title?"selected":""}`} onClick={()=>update({assistant:title})} key={title}><span className="choice-icon">{icon}</span><strong>{title}</strong><small>{copy}</small></button>)}</div>{data.assistant==="Custom workflow"&&<div className="field"><label htmlFor="prompt">Describe what you want to build</label><textarea id="prompt" rows={5} placeholder="I want an assistant that..." value={data.prompt} onChange={e=>update({prompt:e.target.value})}/></div>}</div>;
 if(step===4)return <div className="setup-list">{[["Governed support workspace","Created for your team","ready"],["Assistant profile","Based on your selected goal","ready"],["Approval policy","External changes require review","ready"],["Knowledge workspace","Ready for your approved sources","later"]].map(([name,copy,status])=><div className="setup-row" key={name}><span className="icon-box">{status==="ready"?"✓":"+"}</span><div><b>{name}</b><small>{copy}</small></div><span className={`status ${status}`}>{status==="ready"?"READY":"SET UP LATER"}</span></div>)}</div>;
 if(step===5)return <div><div className="setup-list">{channels.map((name)=><ChannelRow key={name} name={name} state={data.channels[name]} update={state=>update({channels:{...data.channels,[name]:state}})}/>)}</div><p className="soft" style={{fontSize:11,marginTop:15}}>SMS, API/SDK, and other providers can be configured later from your dashboard.</p></div>;
 return <div className="summary"><div className="summary-card"><h3>Your details</h3><p>{data.name||"Your name"} · {data.email||"Your email"}</p><p>{data.role||"Role not selected"}</p></div><div className="summary-card"><h3>Workspace direction</h3><p>{data.company||"Your company"} · {data.industry||"Industry not selected"}</p><p>Starting with {data.goal||"a useful workflow"} using {data.assistant||"an Aegis assistant"}.</p></div><div className="notice success"><strong>Ready for a governed first run.</strong><br/>Aegis will start with reviewable defaults. You can change channels, policies, and autonomy inside the workspace.</div></div>;
}
function ChannelRow({name,state,update}:{name:string;state:ChannelState;update:(state:ChannelState)=>void}){const unavailable=state==="soon";return <div className="setup-row"><span className="icon-box">{name==="API / SDK"?"{}":name==="Voice"?"◉":"⌁"}</span><div><b>{name}</b><small>{state==="connected"?"Connected and ready":state==="ready"?"Connect when you’re ready":state==="later"?"Set up later in the app":"Not available in this preview"}</small></div>{state==="ready"&&!unavailable?<button type="button" className="button ghost small" onClick={()=>update("connected")}>Connect</button>:state==="connected"?<span className="status ready">CONNECTED ✓</span>:<span className={`status ${state}`}>{state==="later"?"SET UP LATER":"COMING SOON"}</span>}</div>}
